# Generated by Django 4.2.3 on 2023-07-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='upload',
            field=models.ImageField(blank=True, upload_to='static/'),
        ),
    ]
