# Generated by Django 4.2.3 on 2023-07-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='upload',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
