# Generated by Django 4.2.3 on 2023-07-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_blog_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='upload',
            field=models.ImageField(blank=True, upload_to='blog_images/'),
        ),
    ]
